In [15]:
import torch 
import torch.nn as nn

In [16]:
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,3.0])

In [17]:
neuron=nn.Linear(in_features=3,out_features=1)
outpu=neuron(inputs)
print(outpu)

tensor([1.5244], grad_fn=<ViewBackward0>)


In [18]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [19]:
neuron.weight @inputs +neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)